site_name: Rede Cafuringa
site_description: 'Repositório de projeto da disciplina de REQ-T1, 2026.2'
site_author: 'Equipe Bytelab'

theme: 
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  language: pt-BR
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para tema escuro
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: black
      toggle:
        icon: material/brightness-4
        name: Mudar para tema claro
  

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

nav:
  - Início: index.md

  - Visão Geral e Concepção do Projeto: 
    - 1. Cenário Atual do Cliente e do Negócio: unidade1/cenario.md
    - 2. Solução Proposta: unidade1/solucao.md
    - 3. Intervenção Social: unidade1/intervencao.md
    - 4. Estratégias de Engenharia de Software: unidade1/estrategias.md
    - 5. Engenharia de Requisitos: unidade1/requisitos.md
    - 6. Cronograma e Entregas: unidade1/cronograma.md
    - 7. Interação Entre Equipe e Cliente: unidade1/interacao.md

  - Requisitos de Software e Backlog do Produto:
    - 8. Requisitos de Software: unidade2/requisitos.md
    - 9. DoR e DoD: unidade2/dor_dod.md
    - 10. Backlog do Produto: unidade2/backlog.md
    - 11. Lições Aprendidas: unidade2/licoes_aprendidas.md
    - 12. Referências Bibliográficas: unidade2/referencias.md

  - Vídeos Demonstrativos:
      - Unidade 1: videos/unidade1.md
      - Unidade 2: videos/unidade2.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format