site_name: Cafuringa
site_description: 'Repositório de projeto da disciplina de REQ-T1, 2026.2'
site_author: 'Equipe Bytelab'

theme: 
  name: material
  logo: 
  favicon: 
  language: pt-BR
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para tema escuro
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: black
      toggle:
        icon: material/brightness-4
        name: Mudar para tema claro

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

nav:
  - Início: index.md

  - Visão do Produto e Projeto:
      - 1. Cenário Atual do Cliente e do Negócio: visao/cenario.md
      - 2. Solução Proposta: visao/solucao.md
      - 3. Intervenção: visao/intervencao.md
      - 4. Estratégias: visao/estrategias.md
      - 5. Engenharia de Requisitos: visao/engenhariaRequisitos.md
      - 6. Cronograma: visao/cronograma.md
      - 7. Interação entre Equipe e Cliente: visao/interacao.md
      - 8. Requisitos de Software: visao/requisitos.md
      - 9. DoR e DoD: visao/dor&dod.md
      - 10. Itens de Trabalho: visao/backlog.md
      - 11. Lições Aprendidas: visao/licoes.md
      - 12. Referências: visao/referencias.md

  - Vídeos Demonstrativos:
      - Unidade 1: entregas/unidade1.md
      - Unidade 2: entregas/unidade2.md
      - Unidade 3: entregas/unidade3.md
      - Unidade 4: entregas/unidade4.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format